// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4828.TalonII;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController mecanumDriveBaseTalonL1;
    public static SpeedController mecanumDriveBaseTalonL2;
    public static SpeedController mecanumDriveBaseTalonR1;
    public static SpeedController mecanumDriveBaseTalonR2;
    public static RobotDrive mecanumDriveBaseRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        mecanumDriveBaseTalonL1 = new Talon(1, 1);
	LiveWindow.addActuator("Mecanum Drive Base", "Talon L 1", (Talon) mecanumDriveBaseTalonL1);
        
        mecanumDriveBaseTalonL2 = new Talon(1, 2);
	LiveWindow.addActuator("Mecanum Drive Base", "Talon L 2", (Talon) mecanumDriveBaseTalonL2);
        
        mecanumDriveBaseTalonR1 = new Talon(1, 3);
	LiveWindow.addActuator("Mecanum Drive Base", "Talon R 1", (Talon) mecanumDriveBaseTalonR1);
        
        mecanumDriveBaseTalonR2 = new Talon(1, 4);
	LiveWindow.addActuator("Mecanum Drive Base", "Talon R 2", (Talon) mecanumDriveBaseTalonR2);
        
        mecanumDriveBaseRobotDrive41 = new RobotDrive(mecanumDriveBaseTalonL1, mecanumDriveBaseTalonL2,
              mecanumDriveBaseTalonR1, mecanumDriveBaseTalonR2);
	
        mecanumDriveBaseRobotDrive41.setSafetyEnabled(true);
        mecanumDriveBaseRobotDrive41.setExpiration(0.1);
        mecanumDriveBaseRobotDrive41.setSensitivity(0.5);
        mecanumDriveBaseRobotDrive41.setMaxOutput(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
